"""empty message

Revision ID: 0140ec23cf04
Revises: f29b4a2d1a99
Create Date: 2023-03-23 18:15:47.344306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0140ec23cf04'
down_revision = 'f29b4a2d1a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')
        # batch_op.drop_column('vendor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'vendor', ['vendor'], ['id'])
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
