"""empty message

Revision ID: 0296299a0a40
Revises: 91c7442a371d
Create Date: 2023-03-24 14:04:47.415888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0296299a0a40'
down_revision = '91c7442a371d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('None', 'users', ['owner'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
