"""user-upgraded

Revision ID: 25e49650379c
Revises: 5c7a870cf47e
Create Date: 2023-03-24 11:05:46.932403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e49650379c'
down_revision = '5c7a870cf47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('None', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('None', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
