"""notification

Revision ID: 32352d335523
Revises: 1143ed502a22
Create Date: 2023-03-20 23:53:26.731371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32352d335523'
down_revision = '1143ed502a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
