"""notifications update

Revision ID: 37a6b97bb3b0
Revises: e58eca4f123e
Create Date: 2023-03-04 00:04:11.770828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a6b97bb3b0'
down_revision = 'e58eca4f123e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_name')
        batch_op.drop_index('ix_notifications_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_notifications_name', ['name'], unique=False)

    # ### end Alembic commands ###
