"""upgraded6

Revision ID: 5c7a870cf47e
Revises: 361aeba1c608
Create Date: 2023-03-23 20:36:35.264249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7a870cf47e'
down_revision = '361aeba1c608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('planning', 'shopping', 'delivered_unpaid', 'delivered_paid', name='orderstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
