"""upgraded

Revision ID: 93d9356f1128
Revises: 0140ec23cf04
Create Date: 2023-03-23 19:12:47.639146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d9356f1128'
down_revision = '0140ec23cf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.drop_column('vendor')
        batch_op.drop_column('order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('None', 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key('None', 'vendor', ['vendor_id'], ['id'])

    # ### end Alembic commands ###
