"""n user fix again

Revision ID: d30f2a61fa7e
Revises: f863ca67ef9e
Create Date: 2023-03-04 00:59:31.127782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30f2a61fa7e'
down_revision = 'f863ca67ef9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('user_id', 'users', ['user'], ['id'])

    # ### end Alembic commands ###
