"""phonenumber

Revision ID: f29b4a2d1a99
Revises: 32352d335523
Create Date: 2023-03-21 13:29:39.522306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29b4a2d1a99'
down_revision = '32352d335523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Unicode(length=255), nullable=False))
        batch_op.drop_column('_phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_phone_number', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
